export const TOOL_MODES = {
  SELECT:            'SELECT',
  ADD_PLAYER:        'ADD_PLAYER',
  ADD_LINE_STRAIGHT: 'ADD_LINE_STRAIGHT',
  ADD_LINE_CURVE:    'ADD_LINE_CURVE',
  EDIT_NODES:        'EDIT_NODES',
};
export const DEFAULT_TOOL = TOOL_MODES.SELECT;
export const VIEW_MODES = {
  PLAYBOOK:   'PLAYBOOK',
  FORMATION:  'FORMATION',
  PLAY:       'PLAY',
  FIELD:      'FIELD',
};
export const DEFAULT_VIEW = VIEW_MODES.PLAYBOOK;
