export const TOOL_MODES = {
  SELECT:            'SELECT',
  BOX_SELECT:        'BOX_SELECT',
  ADD_PLAYER:        'ADD_PLAYER',
  ADD_LINE_STRAIGHT: 'ADD_LINE_STRAIGHT',
  ADD_LINE_CURVE:    'ADD_LINE_CURVE',
  ADD_FOOTBALL:      'ADD_FOOTBALL',
  ADD_TEXT:          'ADD_TEXT',
};
export const DEFAULT_TOOL = TOOL_MODES.SELECT;
export const VIEW_MODES = {
  PLAYBOOK:   'PLAYBOOK',
  FORMATION:  'FORMATION',
  PLAY:       'PLAY',
  FIELD:      'FIELD',
};
export const DEFAULT_VIEW = VIEW_MODES.PLAYBOOK;
